### PR TITLE
Kayode Week 3 Coderbyte Challenge -- Max Subarray

### PR DESCRIPTION
**Pull request by A-Kayode**
Author: Kayode

Have the function MaxSubarray(arr) take the array of numbers stored in arr and determine the largest sum that can be formed by any contiguous subarray in the array. For example, if arr is [-2, 5, -1, 7, -3] then your program should return 11 because the sum is formed by the subarray [5, -1, 7]. Adding any element before or after this subarray would make the sum smaller.

Example:
Input: [-2, 5, -1, 7, -3]
Output: 11

Input: [1, -2, 0, 3]
Output: 3

### CODE REVIEW

**Comment by CaduceusInc** [comment]
Nice work @A-Kayode. 
I have reviewed this solution and saw that your provided solution did not pass all the test cases. 
Please check out the alternative solution I provided in [max_subarray_pilot.py](https://github.com/OpenWit-Technologies/coderbyte-missions/blob/kayode-week3/week3/kayode/max_subarray_pilot.py) (on your branch) and let me know here if you understand it.
Once you understand it, leave a comment here and I will merge the pull request.

Good job!

**Comment by A-Kayode** [comment]
Hi Wale,
Thank you for the review. I have checked the alternative solution you provided and after going through it, I understand what you did in creating the solution. I appreciate the differing perspective you have shown me as regards to solving this particular challenge.

Thank you,
Kayode

**Comment by CaduceusInc** [comment]
> Hi Wale, Thank you for the review. I have checked the alternative solution you provided and after going through it, I understand what you did in creating the solution. I appreciate the differing perspective you have shown me as regards to solving this particular challenge.
> 
> Thank you, Kayode

Great, did you notice any way to improve the solution I provided?

**Comment by A-Kayode** [comment]
> > Hi Wale, Thank you for the review. I have checked the alternative solution you provided and after going through it, I understand what you did in creating the solution. I appreciate the differing perspective you have shown me as regards to solving this particular challenge.
> > Thank you, Kayode
> 
> Great, did you notice any way to improve the solution I provided?

I don't think it's an improvement but I do think that the max_sum list you used is somewhat redundant. We could have just returned max(subarray_sums) without having to create another list to store it's value and then returning the max of that new list.

**Pull request merged**
